day24
saiyam1814/DevOpsRoadmap2022 pull request #219
Opened 2022-02-07 17:50 UTC by Nejilee

2022-02-07 18:37 UTC, kranurag7 requested changes

2022-02-07 18:37 UTC, kranurag7 commented on Neji Lee/DAY 24 - 54/day 24.md
>    >> Control plane, Kube schedular, Kubernetes API-service, control manager, etcd, kube-proxy, kubelet and docker engine
*controller-manager*

2022-02-07 18:37 UTC, kranurag7 commented on Neji Lee/DAY 24 - 54/day 24.md
> +3.  Practised some concepts in Gloang
*Golang*

2022-02-07 19:27 UTC, kranurag7 commented
@Nejilee Good luck for the LFX mentorship. Keep learning and moving ahead.

2022-02-07 19:27 UTC, merged

2022-02-08 04:04 UTC, Nejilee commented
> @Nejilee Good luck for the LFX mentorship. Keep learning and moving ahead.

Thank you so much. Hope my application will get selected.