Progress till 10-02-22
saiyam1814/DevOpsRoadmap2022 pull request #234
Opened 2022-02-10 18:38 UTC by sadab-halim

2022-02-11 05:43 UTC, kranurag7 commented
@sadab-halim I am pointing out some typos. Don't feel irritated. Just approve the changes. I think this will help you in future when you will be contributing to big projects.

2022-02-11 06:58 UTC, kranurag7 requested changes

2022-02-11 06:58 UTC, kranurag7 commented on Sadab-Halim/10-02-22/AWS_Cloud.md
> +- PowerShekk
```suggestion
- Powershell
```

2022-02-11 06:58 UTC, kranurag7 commented on Sadab-Halim/10-02-22/AWS_Cloud.md
> +- IaC allows you to easily sharem version or inventory your cloud infrastructure.
```suggestion
- IaC allows you to easily share version or inventory your cloud infrastructure.
```

2022-02-11 06:58 UTC, kranurag7 commented on Sadab-Halim/10-02-22/AWS_Cloud.md
> +CloudFormation can be easier for DevOps Engineers who do not have a backgroung in web programming languages.
```suggestion
CloudFormation can be easier for DevOps Engineers who do not have a background in web programming languages.
```

2022-02-11 06:58 UTC, kranurag7 commented on Sadab-Halim/10-02-22/AWS_Cloud.md
> +- Less verbosem you could end up with misconfiguration
```suggestion
- Less verbose you could end up with misconfiguration
- ```

2022-02-11 06:58 UTC, kranurag7 commented on Sadab-Halim/10-02-22/AWS_Cloud.md
> +- Uses programming languages eg. Python Rubym JavaScript
```suggestion
- Uses programming languages eg. Python, Ruby & JavaScript.
```

2022-02-11 17:58 UTC, Rajendraladkat1919 reviewed
Looks good to me.

2022-02-11 18:10 UTC, kranurag7 commented
Thanks for review @Rajendraladkat1919

2022-02-12 04:26 UTC, sadab-halim reviewed
Thanks @kranurag7 for the typos.
I have made the changes.

2022-02-12 05:38 UTC, kranurag7 commented
/lgtm @sadab-halim Thanks for updating the changes.

2022-02-12 05:38 UTC, merged