Added Day 6 progress
saiyam1814/DevOpsRoadmap2022 pull request #245
Opened 2022-02-13 18:41 UTC by orrgato

Completed the pre-requisites , almost. Thinking to skip linux course by edx , It will take too much of time.
I can learn linux more when using it. 
Entering  Advanced stuff tomorrow.

2022-02-13 18:43 UTC, orrgato commented
There are so much video links under each topic . Docket topic has 9 video links .
Is it okay to complete just one video per topic ?

2022-02-13 18:55 UTC, kranurag7 requested changes

2022-02-13 18:55 UTC, kranurag7 commented on Shiwam Verma/day06/day6.md
> +- It's not difficult to write or unnderstand. It's like the next gen of json format.
```suggestion
- YAML is the language which is used in majority in Kubernetes & Docker Compose.
- It's not difficult to write or understand. It's like the next gen of JSON format. 
```

2022-02-13 18:56 UTC, kranurag7 commented
@orrgato Go through the suggestions. If you agree then only commit.

2022-02-13 18:58 UTC, kranurag7 commented
Regarding the doubts, Feel free to ask Saiyam in the discord server. Put you doubts in the `devops-roadmap` channel.

2022-02-14 13:17 UTC, kranurag7 commented
/lgtm @orrgato Keep learning

2022-02-14 13:17 UTC, merged