Progress till 05-03-22
saiyam1814/DevOpsRoadmap2022 pull request #285
Opened 2022-03-05 17:11 UTC by sadab-halim

2022-03-05 17:25 UTC, kranurag7 requested changes

2022-03-05 17:25 UTC, kranurag7 commented on Sadab-Halim/25-02-22/README.md
> +- If we wish to see the layer then you can `run docker history <image-name>`
```suggestion
- If we wish to see the layer then you can `docker history <image-name>`
```

2022-03-05 17:25 UTC, kranurag7 commented on Sadab-Halim/03-03-22/README.md
> +Learnt about Orechstration <br/>
```suggestion
Learnt about Orchestration <br/>
```

2022-03-05 19:11 UTC, sadab-halim reviewed
Thanks for the correction

2022-03-06 05:05 UTC, kranurag7 commented
/lgtm @sadab-halim Keep learning.

2022-03-06 05:06 UTC, merged