day 54 progress
saiyam1814/DevOpsRoadmap2022 pull request #318
Opened 2022-03-28 19:18 UTC by nayabatir1

2022-03-29 08:08 UTC, kranurag7 requested changes

2022-03-29 08:08 UTC, kranurag7 commented on atir-nayab/28-03-2022/pod.md
> +To manage a container, kubernetes needs additional information, such as a restart polucy, which defines what to do with a container when it terminates, or a liveness probe, which defines an action to
```suggestion
To manage a container, kubernetes needs additional information, such as a restart policy, which defines what to do with a container when it terminates, or a liveness probe, which defines an action to detect if a process in a container is still alive from the applications perspective, such as web server responding to http requests.  
```

2022-03-29 08:08 UTC, kranurag7 commented on atir-nayab/28-03-2022/pod.md
> +- if the pod fails to start indefinitely, we can use the kubectl describe command to know what went wrong
```suggestion
- if the pod fails to start indefinitely, we can use the `kubectl describe pod <pod-name>` command to know what went wrong
```

2022-03-29 17:19 UTC, kranurag7 commented
Thank you @nayabatir1 for updating the changes. LGTM

2022-03-29 17:19 UTC, merged

2022-03-29 17:33 UTC, saiyam1814 commented
It's great!!

2022-03-30 16:55 UTC, kranurag7 commented
Yes @nayabatir1 I go through it. It's really good.