day 58 progress
saiyam1814/DevOpsRoadmap2022 pull request #341
Opened 2022-04-08 11:16 UTC by nayabatir1

2022-04-09 15:32 UTC, kranurag7 requested changes

2022-04-09 15:32 UTC, kranurag7 commented on atir-nayab/deployment/nginx-dep.yml
> +apiVersion: apps/v1beta2
```suggestion
apiVersion: apps/v1
```

2022-04-09 15:32 UTC, kranurag7 commented on atir-nayab/06-04-2022/deployment101.md
> +a deployment cotroller provides declarative updates for pods and replicaSets.
```suggestion
a deployment controller provides declarative updates for pods and replicaSets.
```

2022-04-09 15:32 UTC, kranurag7 commented on atir-nayab/08-06-2022/scheduling.md
> +1. he scheduler notices that the new pod you created doesn't have a node assigned to it.
```suggestion
1. The scheduler notices that the new pod you created doesn't have a node assigned to it.
```

2022-04-09 15:32 UTC, kranurag7 commented on atir-nayab/08-06-2022/scheduling.md
> +1. the scheduler assigns a node tothe pod
```suggestion
1. the scheduler assigns a node to the pod
```

2022-04-09 15:32 UTC, kranurag7 commented on atir-nayab/08-06-2022/scheduling.md
> +- toleration is a way of ignoring a taint during scheduling. Tolerations aren't applied to nodes, but rather the pods. if we apply a toleration to teh podSpec, we could 'tolarate' the slow disks on t
```suggestion
- toleration is a way of ignoring a taint during scheduling. Tolerations aren't applied to nodes, but rather the pods. if we apply a toleration to the podSpec, we could 'tolerate' the slow disks on that node and still use it.
```

2022-04-09 15:37 UTC, nayabatir1 commented on atir-nayab/deployment/nginx-dep.yml
> +apiVersion: apps/v1beta2
It will be v1beta2

2022-04-09 15:55 UTC, kranurag7 commented on atir-nayab/deployment/nginx-dep.yml
> +apiVersion: apps/v1beta2
for deployments we will the `apps/v1`. Anything I'm missing here? Please let me know.

2022-04-10 01:45 UTC, kranurag7 commented
@nayabatir1 apologies from my side for being late. You can always create another PR through a different branch.

2022-04-10 01:45 UTC, merged

2022-04-10 01:46 UTC, kranurag7 commented
And Yes I really enjoy reading your notes. Keep it up.